language: ruby

rvm:
 - 2.4.1

services:
  - postgresql
  - redis-server

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - bundle exec rspec
  - bundle exec cucumber

notification:
  email: false

before_script:
  - mkdir travis-phantomjs
  - wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
